format = """
$cmd_duration\
[░▒▓](fg:#b0b0f0)\
$username\
$hostname\
[▓▒░](fg:#b0b0f0 bg:#70a0f0)\
$directory\
[▓▒░](fg:#70a0f0 bg:#404060)\
$git_branch\
$git_status\
$time\
[▓▒░](fg:#404060)\
\n\
$character"""

[cmd_duration]
format = "[\\[$duration\\] ]($style)\n"
style = "bold fg:#a0a9cb"

[username]
show_always = true
format = '[ $user ]($style)'
style_user = "bold fg:#001010 bg:#b0b0f0"
style_root = "bold fg:#904050 bg:#b0b0f0"

[hostname]
ssh_only = true
format = '[@ ]($style)[$hostname ](bold $style)'
style = "fg:#001010 bg:#b0b0f0"

[directory]
format = "[ $path ]($style)"
style = "fg:#e0e0e0 bg:#70a0f0"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = '[ $branch]($style)'
style = "fg:#a0b0d0 bg:#404060"

[git_status]
format = '[$all_status$ahead_behind]($style)'
style = "fg:#a0b0d0 bg:#404060"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ $time ]($style)'
style = "fg:#a0b0d0 bg:#404060"

