format = """
$cmd_duration\
[░▒▓](#a3aed2)\
$username\
$hostname\
$directory\
[▓▒░](#769ff0)\
$git_branch\
$git_status\
$time\
$character"""

[cmd_duration]
format = '[\[$duration\] ]($style)'
style = "bold fg:#a0a9cb bg:#1d2230"

[username]
show_always = true
format = '[ $user ]($style)'
style_user = "fg:#090c0c bg:#a3aed2"
style_root = "bold fg:#8c4351 bg:#a3aed2"

[hostname]
#ssh_only = false
format = '[ @ $hostname ]($style)'
style = "fg:#090c0c bg:#a3aed2"

[directory]
format = "[ $path ]($style)"
style = "fg:#e3e5e5 bg:#769ff0"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = '[[ $branch ](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"

[git_status]
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'
style = "bg:#394260"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[ $time ]($style)'
style = "fg:#a0a9cb bg:#1d2230"

